import { Money } from "@/components/currency";
import { Pagination } from "@/components/pagination";
import { TaxPaymentForm } from "@/components/tax-payment-form";
import { getAccounts, getPeriodSummary, getTaxData } from "@/lib/data";

export const metadata={title:"Tax"};
export default async function Tax({searchParams}:{searchParams:Promise<{page?:string}>}){const q=await searchParams;const month=new Date().toISOString().slice(0,7);const[liabilities,accounts,summary]=await Promise.all([getTaxData(Math.max(1,Number(q.page)||1)),getAccounts(),getPeriodSummary(month)]);return <><header className="page-header"><div><div className="eyebrow">Five percent reserve</div><h1>Tax</h1><p className="muted">Liability is reserved on income. Cash moves only when you pay.</p></div></header>
  <section className="grid summary-grid"><div className="card summary-card wide"><span className="muted">Outstanding tax</span><Money value={summary.taxGenerated-summary.taxPaid} className="large"/><span className="small">Across {summary.openTaxCount} open liabilities</span></div><div className="card summary-card"><span className="muted small">Generated</span><Money value={summary.taxGenerated} className="medium"/></div><div className="card summary-card"><span className="muted small">Paid</span><Money value={summary.taxPaid} className="medium"/></div></section>
  <section className="section"><div className="section-title"><h2>Income liabilities</h2><span className="muted small">{liabilities.count} total</span></div><div className="grid">{liabilities.items.map(row=>{const due=Number(row.amount_pkr)-Number(row.paid_pkr);return <article className="card" key={row.id}><div style={{display:"flex",justifyContent:"space-between",gap:15}}><div><span className="chip">{row.status}</span><h3 style={{marginTop:14,marginBottom:4}}>{row.income_description}</h3><span className="muted small">{row.income_date} · {row.tax_percentage}% of income</span></div><div style={{textAlign:"right"}}><Money value={due} className="medium"/><div className="muted small">of <Money value={row.amount_pkr}/></div></div></div>{due>0&&<TaxPaymentForm liabilityId={row.id} outstanding={due} accounts={accounts}/>}</article>})}{!liabilities.items.length&&<div className="card empty">Taxable income will appear here.</div>}</div><Pagination page={liabilities.page} total={liabilities.count} pathname="/tax"/></section>
  </>}
