import { Money } from "@/components/currency";
import { TaxPaymentForm } from "@/components/tax-payment-form";
import { getAccounts, getOpenTaxGroups, getPeriodSummary } from "@/lib/data";

export const metadata={title:"Tax"};
export default async function Tax(){const month=new Date().toISOString().slice(0,7);const[groups,accounts,summary]=await Promise.all([getOpenTaxGroups(),getAccounts(),getPeriodSummary(month)]);const outstanding=groups.reduce((total,group)=>total+group.outstandingPkr,0);const openCount=groups.reduce((total,group)=>total+group.liabilityCount,0);return <><header className="page-header"><div><div className="eyebrow">Tax reserve</div><h1>Tax</h1><p className="muted">Outstanding tax is combined by rate. Payments automatically settle the oldest income first.</p></div></header>
  <section className="grid summary-grid"><div className="card summary-card wide"><span className="muted">Outstanding tax</span><Money value={outstanding} className="large"/><span className="small">Across {openCount} open income {openCount===1?"entry":"entries"}</span></div><div className="card summary-card"><span className="muted small">Generated</span><Money value={summary.taxGenerated} className="medium"/></div><div className="card summary-card"><span className="muted small">Paid</span><Money value={summary.taxPaid} className="medium"/></div></section>
  <section className="section"><div className="section-title"><h2>Outstanding tax containers</h2><span className="muted small">{groups.length} {groups.length===1?"rate":"rates"}</span></div><div className="grid">{groups.map(group=><article className="card" key={group.taxPercentage}><div style={{display:"flex",justifyContent:"space-between",gap:15}}><div><span className="chip">{group.taxPercentage}% tax</span><h3 style={{marginTop:14,marginBottom:4}}>{group.liabilityCount} income {group.liabilityCount===1?"entry":"entries"} combined</h3><span className="muted small">One payment can cover all or part of this balance</span></div><div style={{textAlign:"right"}}><Money value={group.outstandingPkr} className="medium"/><div className="muted small">outstanding</div></div></div><TaxPaymentForm taxPercentage={group.taxPercentage} outstanding={group.outstandingPkr} accounts={accounts}/></article>)}{!groups.length&&<div className="card empty">All tax is paid. New taxable income will appear here.</div>}</div></section>
  </>}
