import Link from "next/link";
import { HandCoins, Search } from "lucide-react";
import { LoanForm } from "@/components/loan-form";
import { Money } from "@/components/currency";
import { Pagination } from "@/components/pagination";
import { getAccounts, getLoanContacts, getLoanEntries, getLoanSummary, getSettings } from "@/lib/data";

export const metadata={title:"Loans"};
export default async function Loans({searchParams}:{searchParams:Promise<{search?:string;person?:string;peoplePage?:string;activityPage?:string}>}){
  const q=await searchParams;const[accounts,contacts,settings,entries,summary]=await Promise.all([getAccounts(),getLoanContacts(q.search,Math.max(1,Number(q.peoplePage)||1)),getSettings(),getLoanEntries(q.person,Math.max(1,Number(q.activityPage)||1)),getLoanSummary()]);
  return <><header className="page-header"><div><div className="eyebrow">Money owed to you</div><h1>Loans</h1><p className="muted">Track what you gave each person and every payment returned.</p></div></header>
    <section className="grid summary-grid"><div className="card summary-card wide"><span className="muted">Still outstanding</span><Money value={summary.outstanding} className="large"/><span className="small">Across {summary.peopleWithBalance} people</span></div><div className="card summary-card"><span className="muted small">Total lent</span><Money value={summary.totalLent} className="medium"/></div><div className="card summary-card"><span className="muted small">Returned</span><Money value={summary.totalReturned} className="medium"/></div></section>
    <section className="section"><div className="section-title"><h2>Add loan activity</h2></div><LoanForm accounts={accounts} contacts={contacts.items} settings={settings}/></section>
    <section className="section"><div className="section-title"><h2>People</h2><span className="muted small">{contacts.count} found</span></div><div className="toolbar"><form><input name="search" placeholder="Search a person…" defaultValue={q.search}/><button className="btn"><Search size={16}/>Search</button></form></div><div className="grid summary-grid">{contacts.items.map(contact=><Link href={`/loans?person=${contact.id}`} className="card" key={contact.id}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><span className="account-icon"><HandCoins size={18}/></span><span className="chip">{contact.entryCount} entries</span></div><h3>{contact.name}</h3><p className="muted small">Outstanding</p><Money value={contact.outstandingPkr} className="medium"/><div className="muted small" style={{marginTop:12}}>Gave <Money value={contact.totalLentPkr}/> · Returned <Money value={contact.totalReturnedPkr}/></div></Link>)}{!contacts.items.length&&<div className="card empty span-2">No matching people found.</div>}</div><Pagination page={contacts.page} total={contacts.count} pathname="/loans" pageParam="peoplePage" query={{search:q.search,person:q.person,activityPage:q.activityPage}}/></section>
    <section className="section"><div className="section-title"><h2>{q.person?"Person history":"Recent loan activity"}</h2>{q.person&&<Link className="chip" href="/loans">Show everyone</Link>}</div><div className="card transaction-list">{entries.items.map(entry=>{const returned=entry.entry_type==="repayment";return <article className="transaction-row" key={entry.id}><span className="tx-icon"><HandCoins size={18}/></span><div className="tx-main"><strong>{entry.loan_contacts.name}</strong><span>{returned?"Returned to":"Given from"} {entry.transactions?.accounts?.name??"account"} · {entry.entry_date}</span></div><div className={`tx-value ${returned?"credit":""}`}>{returned?"+":"−"}<Money value={entry.original_amount} currency={entry.original_currency}/></div></article>})}{!entries.items.length&&<div className="empty">No loan activity yet.</div>}</div><Pagination page={entries.page} total={entries.count} pathname="/loans" pageParam="activityPage" query={{search:q.search,person:q.person,peoplePage:q.peoplePage}}/></section>
  </>
}
